apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledna-app
  namespace: salim-ledna
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ledna-app
  template:
    metadata:
      labels:
        app: ledna-app
    spec:
      containers:
        - name: ledna-app
          image: 487620625686.dkr.ecr.eu-north-1.amazonaws.com/salim-ledna-app:3
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
